### ISSUE TITLE
Wrong Display of GitHub Starts

### ISSUE THREAD

**Issue by comerc** [dabbott/react-native-express#32]
https://github.com/dabbott/react-native-express/blob/master/src/pages/ComponentLibraries.js

![2017-05-10 23 13 49](https://cloud.githubusercontent.com/assets/1025241/25919153/702f1880-35d6-11e7-91e0-8c50a4d6d8db.png)

(Current actual value is 2053)

**Comment by BioGeek** [comment]
This is because of a bug in the [`addCommas`](https://github.com/dabbott/react-native-express/blob/0bc5880b22f44138a409623a0d6d6aa014878515/src/components/StarCount.js#L3) function. 

    return Math.floor(n / 1000).toString() + ',' + n % 1000

If the `n % 1000` part returns a number below 100, then we need to prepend leading zero(s).

See [here](https://stackoverflow.com/q/2901102/50065) for more robust implementations.

**Comment by dabbott** [comment]
Thanks! I used the first implementation 😄 . Fixed on master.
